on:
  push:
    branches:
      - master

jobs:
  build_docs:
    runs-on: ubuntu-latest
    name: Build Docs
    steps:
    - uses: actions/checkout@v1

    - name: Build Documentation
      uses: nikeee/docfx-action@v1.0.0
      with:
        args: docfx.json

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _site
        publish_branch: gh-pages
